module.exports = {
  usage: {
    Basic: [
      {
        type: 'autogenerated',
        dirName: 'basic',
      }
    ],
    Navigation: [{
      type: 'autogenerated',
      dirName: 'navigation',
    }],
    Entities: [
      {
        type: 'autogenerated',
        dirName: 'entities',
      }
    ],
    Categories: [
      {
        type: 'autogenerated',
        dirName: 'categories',
      }
    ],
  },
  setup: {
    Setup: ['setup/prerequisites', 'setup/download'],
    Configuration: ['configuration/basic', 'configuration/options'],
    Remove: ['setup/remove'],
  },
  'developer documentation': {
    'HACS Development': [
      {
        type: 'autogenerated',
        dirName: 'developer',
      }
    ],
    'Publish to HACS': [
      'publish/start',
      'publish/appdaemon',
      'publish/integration',
      'publish/plugin',
      'publish/python_script',
      'publish/theme',
      'publish/include',
      'publish/action',
      'publish/remove',
    ],
  },
  FAQ: [
      {
        type: 'autogenerated',
        dirName: 'faq',
      },
    ],
}
