module.exports = {
  "user": {
    "User documentation": [
      {
        "type": "autogenerated",
        "dirName": "user"
      },
      {
        "Download": [
          {
            "type": "autogenerated",
            "dirName": "setup"
          }
        ]
      },
      {
        "Configuration": [
          {
            "type": "autogenerated",
            "dirName": "configuration"
          }
        ]
      },
      {
        "Categories": [
          {
            "type": "autogenerated",
            "dirName": "categories"
          }
        ]
      },
      {
        "Usage": [
          {
            "type": "autogenerated",
            "dirName": "basic"
          }
        ]
      },
      {
        "Entities": [
          {
            "type": "autogenerated",
            "dirName": "entities"
          }
        ]
      },
      "community_guides"
    ]
  },
  "publisher": {
    "Publisher documentation": [
      {
        "type": "autogenerated",
        "dirName": "publisher"
      },
      {
        "type": "autogenerated",
        "dirName": "publish"
      }
    ]
  },
  "developer": {
    "Developer documentation": [
      {
        "type": "autogenerated",
        "dirName": "developer"
      }
    ]
  },
  "faq": {
    "FAQ": [
      {
        "type": "autogenerated",
        "dirName": "faq"
      }
    ]
  }
} 
