name = "hacs-documentation"
account_id = "4ef0e0b43b821a981b4173298e18bf53"
worker_dev = true
type = "javascript"


kv_namespaces = [ 
         { binding = "KV", id = "63e0db68c9ac4d3eb3e79469f76e5a51"}
]

[triggers]
crons = ["*/15 * * * *"]