import requests
import json
import os
print(os.environ['TOKEN'])

BASE = """---
id: default_repositories
title: Default repositories
description: "Default repositories in HACS"
---
<!-- The content of this file is autogenerated during build with script/generate_default_repositories.py -->
"""

blacklist = requests.get('https://raw.githubusercontent.com/hacs/default/master/blacklist')
blacklist = json.loads(blacklist.text.lower())

for category in ["integration", "plugin", "appdaemon", "python_script", "theme"]:
    response = requests.get(f'https://raw.githubusercontent.com/hacs/default/master/{category}')
    repos = json.loads(response.text.lower())
    for repo in repos:
        if repo in blacklist:
            repos.remove(repo)

    title = category.replace("_", " ").title() + 's' if category != 'appdaemon' else 'AppDaemon Apps'
    BASE += f"\n## {title} ({len(repos)})\n"
    for repo in sorted(repos):
        BASE += f"- [{repo}]({repo})\n"

with open("documentation/default_repositories.md", "w") as mdfile:
    mdfile.write(BASE)
