import requests
import json
import os

BASE = """---
id: default_repositories
title: Default repositories
description: "Default repositories in HACS"
---

Dedicated unofficial website to browse repositories: <a href='https://hacs-repositories.web.app/' target='_blank'>hacs-repositories.web.app</a>

<!-- The content of this file is autogenerated during build with script/generate_default_repositories.py -->
"""

for category in ["integration", "plugin", "appdaemon", "netdaemon", "python_script", "theme"]:
    response = requests.get(f'https://raw.githubusercontent.com/hacs/default/master/{category}')
    repos = json.loads(response.text.lower())

    title = category.replace("_", " ").title() + 's' 
    if category == 'appdaemon':
        title = 'AppDaemon Apps'
    elif category == 'netdaemon':
        title = 'NetDaemon Apps'

    BASE += f"\n## {title}\n\n"
    BASE += f"_{len(repos)} Repositories in total._\n\n"
    for repo in sorted(repos):
        BASE += f"<p className='defaultrepo'><a href='https://github.com/{repo}' target='_blank'>{repo}</a></p>\n"

with open("documentation/default_repositories.md", "w") as mdfile:
    mdfile.write(BASE)
