#!/bin/bash
# curl -sfSL https://hacs.xyz/install | bash -

if [ -z "$(command -v wget)" ]; then
    echo "wget is not installed"
    exit
fi

if [ -z "$(command -v unzip)" ]; then
    echo "unzip is not installed"
    exit
fi

echo "Trying to find the correct directory"

if [ -f "$PWD/home-assistant.log" ]; then
    echo "Current directory is correct"

elif [ -f "/config/home-assistant.log" ]; then
    echo "Changing directory to /config"
    cd /config || exit

elif [ -f "$HOME/.homeassistant/home-assistant.log" ]; then
    echo "Changing directory to $HOME/.homeassistant"
    cd "$HOME/.homeassistant" || exit

elif [ -f "$HOME/homeassistant/home-assistant.log" ]; then
    echo "Changing directory to $HOME/homeassistant"
    cd "$HOME/homeassistant" || exit

elif [ -f "/usr/share/hassio/homeassistant/home-assistant.log" ]; then
    echo "Changing directory to /usr/share/hassio/homeassistant"
    cd /usr/share/hassio/homeassistant || exit

elif [ -n "${HA_DIR}" ]; then
    echo "Changiing direcotry to ${HA_DIR}"
    cd "${HA_DIR}" || exit

else
    echo "Could not find the directory for Home Assistant."
    echo "Manually change the directory to the root of your Home Assistant configuration"
    echo "With the user that is running Home Assistant"
    echo "and run the script again"
    exit
fi

if [ ! -d "$PWD/custom_components" ]; then
    echo "Creating custom_components directory"
    mkdir custom_components
fi

echo "Changing to the custom_components directory"
cd custom_components || exit

if [ -d "$PWD/hacs" ]; then
    echo "HACS directory already exists, exiting"
    rm -rf ./hacs/*
else
    echo "Creating HACS directory"
    mkdir ./hacs
fi

echo "Downloading and installing HACS"
wget -qO- "https://github.com/hacs/integration/releases/latest/download/hacs.zip" | unzip -d /config/custom_components/hacs -

echo "Installation completed"
echo
echo "Remember to restart Home Assistant before you configure it"
